#!/bin/bash
# T13: Catalog all stream-json event types into a spec file
# Aggregates findings from T01-T04 into a comprehensive event catalog
# Depends on: T01, T02, T03, T04
set -euo pipefail

RESULTS_DIR="$(dirname "$0")/results"
mkdir -p "$RESULTS_DIR"

echo "=== T13: Cataloging all stream-json event types ==="

CATALOG="$RESULTS_DIR/stream-json-event-catalog.md"

python3 << 'PYEOF'
import json, glob, os

results_dir = "results"
catalog_file = os.path.join(results_dir, "stream-json-event-catalog.md")

# Collect all events from all test outputs
all_events = {}  # type -> list of example events
all_fields = {}  # type -> set of all fields seen

jsonl_files = glob.glob(os.path.join(results_dir, "*.jsonl"))

if not jsonl_files:
    print("SKIP: no JSONL files found — run T01-T04 first")
    exit(2)

for f in sorted(jsonl_files):
    test_name = os.path.basename(f)
    for line in open(f):
        try:
            obj = json.loads(line)
        except:
            continue
        t = obj.get("type", "unknown")
        if t not in all_events:
            all_events[t] = {"example": obj, "count": 0, "sources": set()}
        all_events[t]["count"] += 1
        all_events[t]["sources"].add(test_name)

        if t not in all_fields:
            all_fields[t] = set()
        all_fields[t].update(obj.keys())

# Write catalog
with open(catalog_file, "w") as f:
    f.write("# Claude Code stream-json Event Catalog\n\n")
    f.write(f"Generated from {len(jsonl_files)} test output files.\n\n")
    f.write("## Summary\n\n")
    f.write(f"| Event Type | Count | Top-level Fields |\n")
    f.write(f"|-----------|-------|------------------|\n")
    for t in sorted(all_events.keys()):
        fields = ", ".join(sorted(all_fields[t]))
        f.write(f"| `{t}` | {all_events[t]['count']} | {fields} |\n")

    f.write(f"\n## Event Details\n\n")
    for t in sorted(all_events.keys()):
        evt = all_events[t]
        f.write(f"### `{t}`\n\n")
        f.write(f"- **Count across tests:** {evt['count']}\n")
        f.write(f"- **Seen in:** {', '.join(sorted(evt['sources']))}\n")
        f.write(f"- **Fields:** {', '.join(sorted(all_fields[t]))}\n\n")
        f.write(f"**Example:**\n```json\n")
        f.write(json.dumps(evt["example"], indent=2)[:800])
        f.write(f"\n```\n\n")

    # Signal bus mapping
    f.write("## Proposed Signal Bus Mapping\n\n")
    f.write("| stream-json type | Signal bus type | Notes |\n")
    f.write("|-----------------|----------------|-------|\n")

    mapping = {
        "message_start": "spawned",
        "content_block_start": "tool_call (if tool_use) / progress (if thinking/text)",
        "content_block_delta": "output (streaming text) / tool_call (streaming input)",
        "content_block_stop": "(internal, may not need signal)",
        "message_delta": "cost (if has usage)",
        "message_stop": "done",
        "result": "done + cost",
        "ping": "(keepalive, skip)",
    }

    for t in sorted(all_events.keys()):
        mapped = mapping.get(t, "??? (needs manual mapping)")
        f.write(f"| `{t}` | {mapped} |\n")

    f.write("\n---\n\n")
    f.write("*This catalog was auto-generated by t13-catalog-events.sh.*\n")
    f.write("*Review and update manually after running tests.*\n")

print(f"Catalog written to {catalog_file}")
print(f"Event types found: {len(all_events)}")
for t in sorted(all_events.keys()):
    print(f"  {t}: {all_events[t]['count']} occurrences")
print()
print("PASS")
PYEOF
